# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/maxi/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/maxi/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maxi/CLionProjects/SiWiR2-EX2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maxi/CLionProjects/SiWiR2-EX2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/maxi/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/maxi/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxi/CLionProjects/SiWiR2-EX2/CMakeFiles /home/maxi/CLionProjects/SiWiR2-EX2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxi/CLionProjects/SiWiR2-EX2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named waveguide

# Build rule for target.
waveguide: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 waveguide
.PHONY : waveguide

# fast build rule for target.
waveguide/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/build
.PHONY : waveguide/fast

Face.o: Face.cpp.o
.PHONY : Face.o

# target to build an object file
Face.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/Face.cpp.o
.PHONY : Face.cpp.o

Face.i: Face.cpp.i
.PHONY : Face.i

# target to preprocess a source file
Face.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/Face.cpp.i
.PHONY : Face.cpp.i

Face.s: Face.cpp.s
.PHONY : Face.s

# target to generate assembly for a file
Face.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/Face.cpp.s
.PHONY : Face.cpp.s

Vertex.o: Vertex.cpp.o
.PHONY : Vertex.o

# target to build an object file
Vertex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/Vertex.cpp.o
.PHONY : Vertex.cpp.o

Vertex.i: Vertex.cpp.i
.PHONY : Vertex.i

# target to preprocess a source file
Vertex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/Vertex.cpp.i
.PHONY : Vertex.cpp.i

Vertex.s: Vertex.cpp.s
.PHONY : Vertex.s

# target to generate assembly for a file
Vertex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/Vertex.cpp.s
.PHONY : Vertex.cpp.s

waveguide.o: waveguide.cpp.o
.PHONY : waveguide.o

# target to build an object file
waveguide.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/waveguide.cpp.o
.PHONY : waveguide.cpp.o

waveguide.i: waveguide.cpp.i
.PHONY : waveguide.i

# target to preprocess a source file
waveguide.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/waveguide.cpp.i
.PHONY : waveguide.cpp.i

waveguide.s: waveguide.cpp.s
.PHONY : waveguide.s

# target to generate assembly for a file
waveguide.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waveguide.dir/build.make CMakeFiles/waveguide.dir/waveguide.cpp.s
.PHONY : waveguide.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... waveguide"
	@echo "... Face.o"
	@echo "... Face.i"
	@echo "... Face.s"
	@echo "... Vertex.o"
	@echo "... Vertex.i"
	@echo "... Vertex.s"
	@echo "... waveguide.o"
	@echo "... waveguide.i"
	@echo "... waveguide.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

